const {test}=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
const c=require('../miniprogram/data/content');
function setup(){const db={};const routes=[];global.wx={getStorageSync:k=>db[k],setStorageSync:(k,v)=>{db[k]=JSON.parse(JSON.stringify(v));},navigateTo:o=>routes.push(o.url),redirectTo:o=>routes.push(o.url),reLaunch:o=>routes.push(o.url),pageScrollTo:()=>{},showToast:()=>{},showModal:()=>{}};delete require.cache[require.resolve('../miniprogram/utils/storage')];return {db,routes,store:require('../miniprogram/utils/storage')};}
function page(name){let p;global.Page=def=>p=def;const f=path.resolve(__dirname,`../miniprogram/pages/${name}/${name}.js`);delete require.cache[f];require(f);p.data=JSON.parse(JSON.stringify(p.data));p.setData=d=>Object.assign(p.data,d);return p;}
const ev=id=>({currentTarget:{dataset:{id}}});
test('页面闭环可运行，点选组装、错误反馈、复测、印记与首页续玩',()=>{
 const {store,routes}=setup();const intro=page('prologue');intro.onShow();intro.next();intro.next();intro.next();assert.equal(store.read().prologueDone,true);
 const ch=page('chapter');ch.onLoad();ch.onShow();ch.start();for(const m of c.chapter.modules)ch.inspect(ev(m.id));ch.assemble();ch.select(ev('meter'));ch.slotTap(ev('sample'));assert.equal(store.read().assembled.length,0);assert.match(ch.data.feedback,/采样/);
 for(const m of c.chapter.modules){ch.select(ev(m.id));ch.slotTap(ev(m.id));}ch.test();ch.anomaly(ev('a'));assert.equal(store.read().anomalyFound,false);ch.anomaly(ev('b'));ch.remedy(ev('verify'));ch.innovation();ch.innovate(ev('same'));assert.equal(store.read().innovated,false);ch.innovate(ev('bidirectional'));ch.finish();assert.equal(routes.at(-1),'/pages/culture/culture');
 const culture=page('culture');culture.onShow();culture.choose({currentTarget:{dataset:{value:c.actions[0]}}});culture.save();assert.equal(store.read().completed,true);const home=page('home');home.onShow();assert.equal(home.data.percent,100);home.start();assert.equal(routes.at(-1),'/pages/culture/culture');
});
test('触摸拖放命中槽位、外部释放、取消与重复放置',()=>{
 const {store}=setup();for(const e of ['prologue','prologue','mission','start'])store.dispatch(e);for(const m of c.chapter.modules)store.dispatch('inspect',m.id);store.dispatch('assembleStart');const ch=page('chapter');ch.onShow();ch.createSelectorQuery=()=>({selectAll(){return this;},boundingClientRect(cb){cb([{left:0,right:100,top:0,bottom:100,dataset:{id:'sample'}}]);return this;},exec(){}});
 ch.dragStart({...ev('sample'),touches:[{clientX:200,clientY:200}]});ch.dragMove({touches:[{clientX:50,clientY:50}]});ch.dragEnd({changedTouches:[{clientX:50,clientY:50}]});assert.deepEqual(store.read().assembled,['sample']);assert.equal(ch.data.drag,null);
 ch.dragStart({...ev('meter'),touches:[{clientX:200,clientY:200}]});ch.dragMove({touches:[{clientX:300,clientY:300}]});ch.dragEnd({changedTouches:[{clientX:300,clientY:300}]});assert.equal(store.read().assembled.length,1);assert.match(ch.data.feedback,/归位/);ch.dragCancel();assert.equal(ch.dragId,null);
});
test('存档跨模块重载恢复；写入失败提示且保留会话进度，支持重试',()=>{
 const {store}=setup();store.dispatch('prologue');delete require.cache[require.resolve('../miniprogram/utils/storage')];const reopened=require('../miniprogram/utils/storage');assert.equal(reopened.read().prologue,1);
 wx.setStorageSync=()=>{throw Error('quota');};reopened.dispatch('prologue');assert.equal(reopened.read().prologue,2);assert.match(reopened.warning(),/保存失败/);wx.setStorageSync=()=>{};reopened.write(reopened.read());assert.equal(reopened.warning(),'');
});
test('深链进入章节或文化页时前置条件不足会重定向',()=>{const {routes}=setup();page('chapter').onLoad();assert.equal(routes.at(-1),'/pages/prologue/prologue');page('culture').onShow();assert.equal(routes.at(-1),'/pages/prologue/prologue');});
test('章节翻页不能跳过任务，回看不会撤销存档',()=>{const {store}=setup();for(const e of ['prologue','prologue','mission'])store.dispatch(e);const ch=page('chapter');ch.onShow();ch.nextPanel();assert.equal(ch.data.panel,1);ch.nextPanel();assert.equal(ch.data.panel,1);for(const m of c.chapter.modules)ch.inspect(ev(m.id));ch.nextPanel();assert.equal(ch.data.panel,2);ch.nextPanel();assert.equal(ch.data.panel,2);for(const m of c.chapter.modules)ch.placeAt(m.id,m.id);ch.nextPanel();assert.equal(ch.data.panel,3);ch.nextPanel();assert.equal(ch.data.panel,4);ch.nextPanel();assert.equal(ch.data.panel,4);ch.anomaly(ev('b'));ch.nextPanel();assert.equal(ch.data.panel,5);ch.nextPanel();assert.equal(ch.data.panel,5);ch.remedy(ev('verify'));ch.nextPanel();assert.equal(ch.data.panel,6);ch.prevPanel();assert.equal(ch.data.panel,5);assert.equal(store.read().calibrated,true);});
